name: stargan-v2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7
  - ffmpeg<5
  - x264
  - pip:
      - ffmpeg-python~=0.2.0
      - opencv-python~=4.1
      - scikit-image~=0.16.2
      - pillow<8
      - numpy<2
      - scipy~=1.10.1
      - tqdm
      - munch
